[build-system]
requires = ["setuptools>=69"]
build-backend = "setuptools.build_meta"

[project]
name = "oroboros"
version = "0.1.0"
description = "C++ to Python binding generator for nanobind and pybind11"
readme = "README.md"
requires-python = ">=3.12"
license = { file = "LICENSE" }
authors = [
  { name = "Lucas Czech" },
]
dependencies = []

[project.scripts]
oroboros = "oroboros.__main__:main"

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]
