"""Semantic model package for Oroboros."""

from .class_ import (
    CppClass,
    CppClassBase,
    CppClassBindFacet,
    CppClassCppFacet,
    CppClassMembers,
    CppClassDefaults,
    CppClassPyFacet,
    CppField,
    CppFieldBindFacet,
    CppFieldCppFacet,
    CppFieldPyFacet,
)
from .comment import CppDoc, PyDoc, build_py_doc_from_cpp_doc
from .element import CppElement
from .enum import (
    CppEnum,
    CppEnumBindFacet,
    CppEnumCppFacet,
    CppEnumPyFacet,
    CppEnumerator,
    CppEnumeratorBindFacet,
    CppEnumeratorCppFacet,
    CppEnumeratorPyFacet,
)
from .function import (
    CppFunction,
    CppFunctionBindFacet,
    CppFunctionCppFacet,
    CppFunctionPyFacet,
    CppParameter,
    CppParameterBindFacet,
    CppParameterCppFacet,
    CppParameterPyFacet,
)
from .location import SourceLocation
from .member import (
    CppConstructor,
    CppMethod,
    CppConstructorCppFacet,
    CppConstructorPyFacet,
    CppMethodCppFacet,
    CppMethodPyFacet,
)
from .module import CppModule, CppModuleBindFacet, CppModuleCppFacet, CppModuleDefaults, CppModulePyFacet
from .namespace import (
    CppNamespace,
    CppNamespaceBindFacet,
    CppNamespaceCppFacet,
    CppNamespaceDefaults,
    CppNamespacePyFacet,
)
from .operator_ import CppOperator, CppOperatorBind
from .template_ import (
    CppClassTemplate,
    CppClassTemplateDecl,
    CppClassTemplateDeclCppFacet,
    CppClassTemplateDefaults,
    CppClassTemplateInstance,
    CppClassTemplateInstanceCppFacet,
    CppFunctionTemplate,
    CppFunctionTemplateDecl,
    CppFunctionTemplateDeclCppFacet,
    CppFunctionTemplateDefaults,
    CppFunctionTemplateInstance,
    CppFunctionTemplateInstanceCppFacet,
    CppNonTypeTemplateArgument,
    CppNonTypeTemplateParameter,
    CppObservedTemplateInstance,
    CppTemplateArgument,
    CppTemplateParameter,
    CppTemplateTemplateArgument,
    CppTemplateTemplateParameter,
    CppTypeTemplateArgument,
    CppTypeTemplateParameter,
    add_template_instance,
    add_class_template_instance,
    add_function_template_instance,
    add_observed_template_instances,
)
from .type import (
    CppType,
    LValueReferenceCppType,
    NamedCppType,
    PointerCppType,
    RValueReferenceCppType,
    TemplateInstanceCppType,
)
from .visibility import CppVisibility

__all__ = [
    "CppClass",
    "CppClassBase",
    "CppClassBindFacet",
    "CppClassCppFacet",
    "CppClassMembers",
    "CppClassDefaults",
    "CppClassPyFacet",
    "CppClassTemplate",
    "CppClassTemplateDecl",
    "CppClassTemplateDeclCppFacet",
    "CppClassTemplateDefaults",
    "CppClassTemplateInstance",
    "CppClassTemplateInstanceCppFacet",
    "CppConstructor",
    "CppConstructorCppFacet",
    "CppConstructorPyFacet",
    "CppDoc",
    "CppElement",
    "CppEnum",
    "CppEnumBindFacet",
    "CppEnumCppFacet",
    "CppEnumPyFacet",
    "CppEnumerator",
    "CppEnumeratorBindFacet",
    "CppEnumeratorCppFacet",
    "CppEnumeratorPyFacet",
    "CppField",
    "CppFieldBindFacet",
    "CppFieldCppFacet",
    "CppFieldPyFacet",
    "CppFunction",
    "CppFunctionBindFacet",
    "CppFunctionCppFacet",
    "CppFunctionPyFacet",
    "CppFunctionTemplate",
    "CppFunctionTemplateDecl",
    "CppFunctionTemplateDeclCppFacet",
    "CppFunctionTemplateDefaults",
    "CppFunctionTemplateInstance",
    "CppFunctionTemplateInstanceCppFacet",
    "CppMethod",
    "CppMethodCppFacet",
    "CppMethodPyFacet",
    "CppModule",
    "CppModuleBindFacet",
    "CppModuleCppFacet",
    "CppModuleDefaults",
    "CppModulePyFacet",
    "CppNamespace",
    "CppNamespaceBindFacet",
    "CppNamespaceCppFacet",
    "CppNamespaceDefaults",
    "CppNamespacePyFacet",
    "CppOperator",
    "CppOperatorBind",
    "CppParameter",
    "CppParameterBindFacet",
    "CppParameterCppFacet",
    "CppParameterPyFacet",
    "CppNonTypeTemplateArgument",
    "CppNonTypeTemplateParameter",
    "CppObservedTemplateInstance",
    "CppTemplateArgument",
    "CppTemplateParameter",
    "CppTemplateTemplateArgument",
    "CppTemplateTemplateParameter",
    "CppType",
    "CppTypeTemplateArgument",
    "CppTypeTemplateParameter",
    "LValueReferenceCppType",
    "NamedCppType",
    "PointerCppType",
    "PyDoc",
    "RValueReferenceCppType",
    "SourceLocation",
    "TemplateInstanceCppType",
    "CppVisibility",
    "add_template_instance",
    "add_class_template_instance",
    "add_function_template_instance",
    "add_observed_template_instances",
    "build_py_doc_from_cpp_doc",
]
